USE DBEntryTest
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER on
GO

BEGIN

CREATE TABLE dbo.TestTable
(
	ID TINYINT IDENTITY(0,1) NOT NULL,
	[TestName] NVARCHAR(MAX) NOT NULL,
	[TestVal] NVARCHAR(MAX) NULL,

	CONSTRAINT PK_DBENTRY_TEST PRIMARY KEY CLUSTERED
	(
		ID ASC
	)
	WITH
	(
		PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

END